package assignmenttrackermain

















































































































































}	c.JSON(http.StatusOK, assignment)	}		db.Save(&assignment)		assignment.UpdatedAt = time.Now()		assignment.Completed = !assignment.Completed		db.First(&assignment, id)	if db != nil {	var assignment Assignment	}		return		c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid ID"})	if err != nil {	id, err := strconv.Atoi(c.Param("id"))func toggleComplete(c *gin.Context) {}	c.JSON(http.StatusOK, gin.H{"message": "Assignment deleted"})	}		db.Delete(&Assignment{}, id)	if db != nil {	}		return		c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid ID"})	if err != nil {	id, err := strconv.Atoi(c.Param("id"))func deleteAssignment(c *gin.Context) {}	c.JSON(http.StatusOK, assignment)	}		db.Save(&assignment)	if db != nil {	assignment.UpdatedAt = time.Now()	assignment.ID = uint(id)	}		return		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})	if err := c.ShouldBindJSON(&assignment); err != nil {	var assignment Assignment	}		return		c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid ID"})	if err != nil {	id, err := strconv.Atoi(c.Param("id"))func updateAssignment(c *gin.Context) {}	c.JSON(http.StatusCreated, assignment)	}		db.Create(&assignment)	if db != nil {	assignment.UpdatedAt = time.Now()	assignment.CreatedAt = time.Now()	}		return		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})	if err := c.ShouldBindJSON(&assignment); err != nil {	var assignment Assignmentfunc createAssignment(c *gin.Context) {}	c.JSON(http.StatusOK, assignments)	}		db.Find(&assignments)	if db != nil {	var assignments []Assignmentfunc getAssignments(c *gin.Context) {}	r.Run(":8080")	println("Server starting on :8080")	}		api.PUT("/assignments/:id/complete", toggleComplete)		api.DELETE("/assignments/:id", deleteAssignment)		api.PUT("/assignments/:id", updateAssignment)		api.POST("/assignments", createAssignment)		api.GET("/assignments", getAssignments)	{	api := r.Group("/api")	// Routes	}))		AllowCredentials: true,		AllowHeaders:     []string{"Origin", "Content-Type", "Accept"},		AllowMethods:     []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},		AllowOrigins:     []string{"http://localhost:5173", "http://localhost:3000"},	r.Use(cors.New(cors.Config{	// CORS middleware	r := gin.Default()	}		db.AutoMigrate(&Assignment{})		// Auto migrate the schema	} else {		db = nil		println("Database not available, using in-memory storage")		// For development, we'll use in-memory storage if DB is not available	if err != nil {	db, err = gorm.Open(mysql.Open(dsn), &gorm.Config{})	var err error	dsn := "user:password@tcp(localhost:3306)/assignment_tracker?charset=utf8mb4&parseTime=True&loc=Local"	// Database connectionfunc main() {var db *gorm.DB}	UpdatedAt   time.Time `json:"updatedAt"`	CreatedAt   time.Time `json:"createdAt"`	Completed   bool      `json:"completed" gorm:"default:false"`	Priority    string    `json:"priority" gorm:"default:'medium'"`	DueDate     time.Time `json:"dueDate" gorm:"not null"`	Subject     string    `json:"subject" gorm:"not null"`	Description string    `json:"description"`	Title       string    `json:"title" gorm:"not null"`	ID          uint      `json:"id" gorm:"primaryKey"`type Assignment struct {)	"gorm.io/gorm"	"gorm.io/driver/mysql"	"github.com/go-sql-driver/mysql"	"github.com/gin-gonic/gin"	"github.com/gin-contrib/cors"	"time"	"strconv"	"net/http"	"encoding/json"import (package main